### ISSUE TITLE
Experiment: Font sprite rendering

### ISSUE THREAD

**Issue by johnblat** [johnblat64/BirdMazeGame#18]
**why**
BirdMazeGame will feature boiling lines for the animations of characters and objects. It will also feature text that is both stylish and animated with boiling lines. To achieve this, we'll probably want to treat text like any other sprite sheet.

**what**
To achieve this, we need two things:
 1. a system that can take in a std::string or char *, map each character in the string to a sprite in a sprite sheet that contains all the characters in the form of sprites
 2. animations for each letter in the sprite sheet that make it look as though the lines are boiling

Write this in a standalone program. We will implement this into the game later. 

Focus on 1 for this issue(a system that can take in a std::string or char *, map each character in the string to a sprite in a sprite sheet that contains all the characters in the form of sprites)

We'll do 2 in a separate issue.

**sprite sheet to use as example**: https://forum.thegamecreators.com/xt/xt_apollo_pic.php?i=2489099, though you can use whatever sprite sheet you want as long as it has an alphabet

**Comment by arxeous** [comment]
https://github.com/arxeous/Text-Rendering-Test
